### PR TITLE
Shuffled display of the top images

### PR DESCRIPTION
**Pull request by Tazzios**
This pull request will add an extra field "Number of images to randomize" so that you can randomize your images without a date selection. This way it will always show pictures without being static.

I created this because the amount of new images on my site each week varies very much, sometimes 200 sometimes none for weeks, and i want it to show the top x lastest pictures without being static. I had the following options if I want to show the latest on a not static way:

1.  Order random and set filter on one week which works good when i have around 50 new images, but not for 200 or zero images.
2. Order random and set filter on one month which works good when i have around 50 or zero images new images in a week, but not for 200 in a week.

With this pull the randomize not limited by date selection but by the amount of images you set.

I hope it will make it to the master. :)
It should be save to upgrade without destroying current configured modules

### CODE REVIEW

**Comment by MrMusic** [comment]
Thank you for your PR, it works well.

I would suggest to expand the description to explain the function a bit more.
In particular, I would write that with '0' the shuffle is switched off and the order from the 'Sorting' field is preserved.
I don't know, but maybe the term 'shuffle' instead of 'randomize' would also be good?

**Comment by Tazzios** [comment]
Shuffle is indeed more friendly (and the PHP function that I actually use).
I adjusted the text a bit.

But now i`m seeing that there is an E missing in the translation tag.
JILIMITSeLECTION

And i get new ideas like:
JISHUFFLE="Number of images to use for shuffle" 

So i will follow up with another edit this week.

**Comment by MrMusic** [comment]
I would also recommend moving the new and changed language constants to the end of the file, as in 3.4.1, for example.

**Comment by Tazzios** [comment]
Updated the translation of the new string, moved to the end and undo the JILMIT edit.

**Comment by MrMusic** [comment]
Thanks, but I think there are small 'style' problems.
Perhaps you would like to adopt these changes? https://github.com/MrMusic/Tazzios-JoomImages/compare/Fix-small-problems

**Comment by Tazzios** [comment]
Could not figure out how to pull your adjustments, so I did copy and paste file contents.

Though I did not remove the string 'JIJUSTIFIEDBORDERDESC' as I do not know why, and it has nothing to do with my feature.
(edit: i see, in your comment it was double.) 

Also renamed the parameter name to shuffle to make it more clear in the code.

**Comment by MrMusic** [comment]
>Could not figure out how to pull your adjustments, so I did copy and paste file contents.

Unfortunately I could not create a PR either, so the only thing left to do is to copy the change by hand.

>Though I did not remove the string 'JIJUSTIFIEDBORDERDESC' as I do not know why, and it has nothing to do with my feature.
(edit: i see, in your comment it was double.)

Yes, exactly. You probably copied the language constant by accident when you add the language constants at the end.

**Comment by Tazzios** [comment]
All our suggested changes are now also in this pull request.

**Comment by MrMusic** [comment]
There are still a few small things concerning the code style. 
But otherwise it is ok for me. Thanks!

**Comment by Tazzios** [comment]
Ow sorry, though I had all the code style covert with this commit: https://github.com/Tazzios/JoomImages/commit/bbdbd8c0af3f2293ef891ed878baf1ee0d415774

**Comment by Erftralle** [comment]
Thanks for your contribution.

It took some time before I understood what you want to achieve with the proposed parameter. Although I find it a little bit exotic it might be usefull for some users.

- I would propose to improve the decription of the parameter. Maybe there some more people than me having problems to understand the function of the parameter. What do you think of:

_Enter the number of images, which will serve as the base number of images for a shuffled display of the "Number of images" and the "Sorting" selected above. For example, if you want to show a random selection of 3 of the 50 best rated images then select 50 here, 3 for "Number of images" and "Rating descending" for "Sorting". Another example, if you want to show a random display of 10 of the 100 newest images then select 100 here, 10 for "Number of images" and "ID descending" for "Sorting". "The number of images to use for shuffle" needs to be greater or equal then the 'Number of images'. Leave empty to disable the shuffling mode."_

- What do you think? The new parameter should be checked to be greater equal to the "Number of images".

- When the objects array is shuffled it must be secured that the array keys will be preserved that means will also be shuffled. The keys are the image IDs and are used for instance in the function getLastComments() line 761. The function shuffle destroys the original keys which will cause errors in other parts of the module code. So you must think about a method to preserve the keys.

**Comment by Tazzios** [comment]
1. That is a lot of text. I would keep it at one example and change 'random' for 'shuffle' to stay consistence. 
2. It would benice, but I do not know if a check in the xml is possible. Worst case you see an image less.
3. I do not see a different in the var_dump before and after the shuffle, so i am not aware of anything going wrong.
Before shuffle selecting 3 images and showing 2:
`	[5]=> object(stdClass)#1165 (9) 
	{ ["id"]=> string(1) "5" ["catid"]=> string(1) "3" ["imgthumbname"]=> string(33) "afbeeld_4_20211003_1023719045.png" ["imgfilename"]=> string(33) "afbeeld_4_20211003_1023719045.png" ["imgtitle"]=> string(9) "afbeeld_4" ["imgtext"]=> string(0) "" ["imgdate"]=> string(19) "2021-10-03 15:31:35" ["ccid"]=> string(1) "3" ["catpath"]=> string(8) "categ2_3" } 
	[4]=> object(stdClass)#1166 (9) 
	{ ["id"]=> string(1) "4" ["catid"]=> string(1) "3" ["imgthumbname"]=> string(33) "afbeeld_3_20211003_1445327881.png" ["imgfilename"]=> string(33) "afbeeld_3_20211003_1445327881.png" ["imgtitle"]=> string(9) "afbeeld_3" ["imgtext"]=> string(0) "" ["imgdate"]=> string(19) "2021-10-03 15:31:35" ["ccid"]=> string(1) "3" ["catpath"]=> string(8) "categ2_3" } 
	[3]=> object(stdClass)#1167 (9) 
	{ ["id"]=> string(1) "3" ["catid"]=> string(1) "3" ["imgthumbname"]=> string(33) "afbeeld_2_20211003_2060435418.png" ["imgfilename"]=> string(33) "afbeeld_2_20211003_2060435418.png" ["imgtitle"]=> string(9) "afbeeld_2" ["imgtext"]=> string(0) "" ["imgdate"]=> string(19) "2021-10-03 15:31:35" ["ccid"]=> string(1) "3" ["catpath"]=> string(8) "categ2_3" }`
After shuffle: 
`[0]=> object(stdClass)#1165 (9) 
	{ ["id"]=> string(1) "5" ["catid"]=> string(1) "3" ["imgthumbname"]=> string(33) "afbeeld_4_20211003_1023719045.png" ["imgfilename"]=> string(33) "afbeeld_4_20211003_1023719045.png" ["imgtitle"]=> string(9) "afbeeld_4" ["imgtext"]=> string(0) "" ["imgdate"]=> string(19) "2021-10-03 15:31:35" ["ccid"]=> string(1) "3" ["catpath"]=> string(8) "categ2_3" } 
	[1]=> object(stdClass)#1166 (9) 
	{ ["id"]=> string(1) "4" ["catid"]=> string(1) "3" ["imgthumbname"]=> string(33) "afbeeld_3_20211003_1445327881.png" ["imgfilename"]=> string(33) "afbeeld_3_20211003_1445327881.png" ["imgtitle"]=> string(9) "afbeeld_3" ["imgtext"]=> string(0) "" ["imgdate"]=> string(19) "2021-10-03 15:31:35" ["ccid"]=> string(1) "3" ["catpath"]=> string(8) "categ2_3" }`

**Comment by Erftralle** [comment]
> That is a lot of text. I would keep it at one example and change 'random' for 'shuffle' to stay consistence.

What is the problem with a long description? Better to explain once too much than once too little. There is absolutely no reason for me to delete an example. As for the swap from "random" to "shuffled", I would be fine.

> It would benice, but I do not know if a check in the xml is possible. Worst case you see an image less.

Not in the XML file but in the PHP code file.

> I do not see a different in ...

The difference are the array keys which are the image IDs.
Before:
**[5]**=> object(stdClass)#1165 ... 
**[4]**=> object(stdClass)#1166 ...
**[3]**=> object(stdClass)#1167
After:
**[0]**=> object(stdClass)#1165 ...
**[1]**=> object(stdClass)#1166 ...

After the shuffle the ID of the image object 1165 has changed from 5 to 0. This will cause errors in other parts of the module code (see my last comment).

**Comment by Tazzios** [comment]
You asked my opinion, I`m a short with words guy. :) 
I updated the text with the  long description and added some breaks to make it easier to read.

At this page I found a solution for the keys which I also implemented: 
https://www.php.net/manual/en/function.shuffle.php

**Comment by Erftralle** [comment]
Thank you very much.
I will merge your pull request now although there are still some optimizations possible as well as some code style issues to fix.I' ll do that in a separate pull request and will ask you to review the changes.

**Pull request merged**
